//! Shared output paths and file writing for media jobs and their manifests.

use std::io;
use std::path::{Path, PathBuf};

/// The file stem of `base`, or `"image"` if it has none.
pub(crate) fn base_stem(base: &Path) -> String {
    base.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "image".to_string())
}

/// Join `name` onto `base`'s parent directory (or use it bare when there is none).
pub(crate) fn in_parent_of(base: &Path, name: String) -> PathBuf {
    match base.parent() {
        Some(p) if !p.as_os_str().is_empty() => p.join(name),
        _ => PathBuf::from(name),
    }
}

/// Write generated bytes to `path`, creating missing parent directories first.
/// A parent-creation failure is deliberately ignored here: the write that
/// follows reports the real error with the full path.
pub async fn write_bytes(path: &Path, bytes: &[u8]) -> io::Result<()> {
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        tokio::fs::create_dir_all(parent).await.ok();
    }
    tokio::fs::write(path, bytes).await
}
