//! Shared output-file helper for the audio, image, and video job runners.

use std::io;
use std::path::Path;

/// Write generated bytes to `path`, creating missing parent directories first.
/// A parent-creation failure is deliberately ignored here: the write that
/// follows reports the real error with the full path.
pub async fn write_bytes(path: &Path, bytes: &[u8]) -> io::Result<()> {
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        tokio::fs::create_dir_all(parent).await.ok();
    }
    tokio::fs::write(path, bytes).await
}
