//! Shared output paths and file writing for media jobs and their manifests.

use std::io;
use std::path::{Path, PathBuf};

/// The file stem of `base`, or `"output"` if it has none.
pub(crate) fn base_stem(base: &Path) -> String {
    base.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "output".to_string())
}

/// Join `name` onto `base`'s parent directory (or use it bare when there is none).
pub(crate) fn in_parent_of(base: &Path, name: String) -> PathBuf {
    match base.parent() {
        Some(p) if !p.as_os_str().is_empty() => p.join(name),
        _ => PathBuf::from(name),
    }
}

/// The path for output `index_zero_based` of `total`: `base` itself (with
/// `ext`) when it is the only one, else `<stem>-<tag>-<marker>.<ext>` beside
/// it, where `marker` is built from the 1-based index padded by
/// [`padded_index`].
pub(crate) fn numbered_path(
    base: &Path,
    tag: &str,
    marker: impl FnOnce(String) -> String,
    index_zero_based: usize,
    total: usize,
    ext: &str,
) -> PathBuf {
    if total <= 1 {
        return base.with_extension(ext);
    }
    let marker = marker(padded_index(index_zero_based, total));
    in_parent_of(base, format!("{}-{tag}-{marker}.{ext}", base_stem(base)))
}

/// The 1-based index, zero-padded to at least three digits (wider when
/// `total` needs it) so a directory listing sorts in output order.
fn padded_index(index_zero_based: usize, total: usize) -> String {
    let width = 3.max(total.to_string().len());
    format!("{:0width$}", index_zero_based + 1)
}

/// Write generated bytes to `path`, creating missing parent directories first.
/// A parent-creation failure is returned as is: the write after it would only
/// say "not found" and hide the cause (a permission error, a full disk).
pub async fn write_bytes(path: &Path, bytes: &[u8]) -> io::Result<()> {
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        tokio::fs::create_dir_all(parent).await?;
    }
    tokio::fs::write(path, bytes).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_path_without_a_stem_is_named_output() {
        assert_eq!(base_stem(Path::new("..")), "output");
        assert_eq!(base_stem(Path::new("clips/take.mp4")), "take");
    }

    #[tokio::test]
    async fn write_bytes_creates_missing_parent_directories() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("a/b/out.bin");
        write_bytes(&path, b"xyz").await.unwrap();
        assert_eq!(std::fs::read(&path).unwrap(), b"xyz");
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn write_bytes_reports_why_the_parent_could_not_be_created() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let locked = dir.path().join("locked");
        std::fs::create_dir(&locked).unwrap();
        std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o555)).unwrap();
        let error = write_bytes(&locked.join("new/out.bin"), b"x")
            .await
            .unwrap_err();
        std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o755)).unwrap();
        assert_eq!(error.kind(), io::ErrorKind::PermissionDenied, "{error}");
    }
}
